package ix.fd.gekinavi.api

data class Movie(
    val id: Int,
//    val externalId: List<String>,
    val name: String,
//    val alternativeName: String,
//    val enName: String,
//    val names: List<NamesForMovie>,
    val type: String,
    val typeNumber: Int,
    val year: Int,
    val description: String,
    val shortDescription: String,
    val slogan: String,
    val status: String,
    val rating: RatingForMovie,
//    val votes: VotesForMovie,
    val movieLength: Int,
    val totalSeriesLength: Int,
    val seriesLength: Int,
    val ratingMpaa: String,
    val ageRating: Int,
    val poster: PosterForMovie,
//    val backdrop: BackdropForMovie,
    val genres: List<GenresForMovie>,
    val countries: List<CountriesForMovie>,
    val persons: List<PersonsForMovie>,
)